### ISSUE TITLE
Documentation error: OpenType tags do not use parameters 

### ISSUE THREAD

**Issue by RGB-es** [silnrsi/font-andika#2]
According to the documentation, this font dropped Graphite and now only offers OpenType features. In the `features.pdf` file, when presenting the available features, there is an error: for OpenType tags, parameters are ignored. Instead of using, as the documentation shows, `smcp=1` you only need to use `smcp` in order to get small caps. 

Tested on LibreOffice and XeTeX.

**Comment by bobh0303** [comment]
This is not a documentation error but we are listing an explicit value to provide maximum clarity. 

Note that, according to [css font feature settings](https://www.w3.org/TR/css-fonts-3/#propdef-font-feature-settings) documentation, the following feature setting values are all equivalent: 
- value is absent
- `1`
- `on`

> for OpenType tags, parameters are ignored.

Parameters (a.k.a feature setting values) are not ignored. It is just that if the parameter is absent then the assumed value is `1`
