### ISSUE TITLE
Double storey A (ss01 and ss13) doesn't affect U+00AA

### ISSUE THREAD

**Issue by aricaldeira** [silnrsi/font-andika#3]
Hi, first of all, thank you so much for this font!

It really helps me work/read with less fatigue.

Tested on LibreOffice 7.4.1.2 on ArchLinux:

![image](https://user-images.githubusercontent.com/185558/195364498-7c267b31-5b57-495d-b02a-e2516612b45b.png)

**Comment by jvgaultney** [comment]
Fixed in v6.200
