### ISSUE TITLE
Sans-serif number 1 (cv01) doesn't affect U+00BC and U+00BD

### ISSUE THREAD

**Issue by aricaldeira** [silnrsi/font-andika#4]
Tested on LibreOffice 7.4.1.2 on ArchLinux:

![image](https://user-images.githubusercontent.com/185558/195367316-59676f7e-1ef3-4d9f-ba49-b039447f2d63.png)

_Note:_ U+2215 _is not part of Andika_

**Comment by aricaldeira** [comment]
Also affects U+2150, U+2151, U+2152, U+2153, U+2155, U+2159, U+215B, U+215F

**Comment by jvgaultney** [comment]
Thank you, Ari - We'll fix this in one of the next two versions. We're also adding new OpenType-based fraction construction code that will form fractions from any combinations of numbers separated by U+2044 FRACTION SLASH.

U+2215 DIVISION SLASH shouldn't be used to construct fractions. Its intended use is for indicating unit of measure divisions, such as m/s (miles per second). We'll add it to the fonts, but it will be identical to U+002F SOLIDUS.

**Comment by aricaldeira** [comment]
Thank you, for the feedback and for the tip!

The difference between U+2044 and U+2215 became really clear,
once I used another font; tested with DejaVu and Noto.

**Comment by jvgaultney** [comment]
Fixed in v6.200
