### ISSUE TITLE
Open top number 4 (cv04) doesn't affect U+00BC and U+00BE

### ISSUE THREAD

**Issue by aricaldeira** [silnrsi/font-andika#5]
Tested on LibreOffice 7.4.1.2 on ArchLinux:

![image](https://user-images.githubusercontent.com/185558/195369111-7c1a035a-5130-4d21-a397-439e95e80cdf.png)

_Note:_ U+2215 _is not part of Andika_

**Comment by aricaldeira** [comment]
Also affects U+2158

**Comment by jvgaultney** [comment]
Fixed in v6.200
