### ISSUE TITLE
Issue with "ff" (2 consecutive "f" characters)

### ISSUE THREAD

**Issue by zanonmark** [silnrsi/font-andika#8]
Hi, and thanks for the Andika font.

I'm writing a Java application which uses Apache PDFBox and the Andika font to write some strings into a PDF.
Everything is working fine, until I write some strings containing "ff" (or multiples: "ffff","ffffff", etc.): at this point the "ff" substring can be displayed in the PDF, but it's not properly selectable, like if it was an image not text.
![image](https://github.com/silnrsi/font-andika/assets/13437344/af58e83e-17c4-46b5-9d31-cb9494e5661b)
![image](https://github.com/silnrsi/font-andika/assets/13437344/22fd2e26-4241-4901-a0a7-67283cf74fcc)

I thought it was an issue with PDFBox, but changing the font to, for example, the included Helvetica gives the expected results.

At the same time, I tried to write some strings in LibreOffice Writer with Andika, and I saw that when writing "ff" the first "f" changes automatically (it becomes larger).
![image](https://github.com/silnrsi/font-andika/assets/13437344/5d471595-401f-4d4b-a6c0-c3658dcb3c45)

Is there some kind of mechanism doing some automatic magic transformation here?
If so, is there some way to disable it from an external software (PDFBox, LibreOffice, etc.)?

Thanks,
MZ

**Comment by bobh0303** [comment]
PDFs should be built such that they contains the underlying text stream. Apparently PDFBox is not doing that and your PDF reader is having to guess at the underlying text based on the glyphs it sees on the page.

For someone else's description of this long-standing issue, take a look at https://superuser.com/a/520055. Note, in particular the last paragraph:
>Applications producing PDFs can opt to include the actual text as metadata. If they don't, you're left at the mercy of how the embedded fonts are handled and whether the PDF reader can piece together the original text again.

**Comment by zanonmark** [comment]
Thanks for pointing me to the right direction; I didn't even know what ligatures were.

I will close the ticket, as it doesn't look like a bug in Andika at all.

Just some quick notes for those who come across the same issue with PDFBox.

1) It looks like the problem lies with PDFBox 3, which started to support ligatures, but apparently doesn't allow to disable them.
I tried to follow [these suggestions](https://www.devgem.io/posts/issue-with-ligatures-in-pdfbox-3-0):
```
TrueTypeFont ttf = new TTFParser().parse(...);
ttf.disableGsubFeature("liga");
PDFont font = PDType0Font.load(doc, ttf, false);
```
but it simply didn't work, and ligatures were still there.
It seems to be a [known issue](https://issues.apache.org/jira/browse/PDFBOX-5700).

2) If You stick with PDFBox 2 (2.0.30 is the last version at the time of writing), You will experience no problem at all: "ff" will be printed as expected, "f" and "f", with no ligatures.

Thanks,
MZ
